### ISSUE TITLE
[Issue] very short issue description

### ISSUE THREAD

**Issue by FeelsBadMan1** [l0c4lh057/AccountSwitcher#32]
Hello,
I have  a issure with the Accountswitcher plugin.
I succesfully added a few accounts but if i use the keybinds i have set to switch the accounts it will login into the account i wanted to. However 5 seconds after the account is switched the Discordclient is closing and i need to manually restart it and only then im logged in into the new Account without the Client is closing. It would be nice, if the closing thing can be fixed somehow its annoying to do this each time.

**Comment by FeelsBadMan1** [comment]
i opend the devconsole while switching and get a error that might help but i dont understand the errorcode:
```
2276137a5d7df04f45db.js:2 Uncaught (in promise) Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch. Action: BILLING_SUBSCRIPTION_FETCH_START Already dispatching: I18N_LOAD_SUCCESS
    at e.exports (https://discord.com/assets/2276137a5d7df04f45db.js:2:325880)
    at e.t._dispatch (https://discord.com/assets/2276137a5d7df04f45db.js:2:2898753)
    at e._dispatch (D:\Downloads\EnhancedDiscord\plugins\0PluginLibrary.plugin.js:1905:73)
    at e.t.dispatch (https://discord.com/assets/2276137a5d7df04f45db.js:2:2898699)
    at https://discord.com/assets/2276137a5d7df04f45db.js:2:847412
    at u (https://discord.com/assets/2276137a5d7df04f45db.js:2:3154272)
    at Generator._invoke (https://discord.com/assets/2276137a5d7df04f45db.js:2:3154025)
    at Generator.forEach.e.<computed> [as next] (https://discord.com/assets/2276137a5d7df04f45db.js:2:3154629)
    at _ (https://discord.com/assets/2276137a5d7df04f45db.js:2:840283)
    at a (https://discord.com/assets/2276137a5d7df04f45db.js:2:840486)
    at https://discord.com/assets/2276137a5d7df04f45db.js:2:840545
    at new Promise (<anonymous>)
    at https://discord.com/assets/2276137a5d7df04f45db.js:2:840426
    at N (https://discord.com/assets/2276137a5d7df04f45db.js:2:847881)
    at t.fetchSubscriptions (https://discord.com/assets/2276137a5d7df04f45db.js:2:838342)
    at https://discord.com/assets/cb8adf5de513780a5699.js:2:1270737
    at gs (https://discord.com/assets/2276137a5d7df04f45db.js:2:3241820)
    at Cu (https://discord.com/assets/2276137a5d7df04f45db.js:2:3267598)
    at t.unstable_runWithPriority (https://discord.com/assets/2276137a5d7df04f45db.js:2:3286470)
    at zi (https://discord.com/assets/2276137a5d7df04f45db.js:2:3208172)
    at Lu (https://discord.com/assets/2276137a5d7df04f45db.js:2:3267361)
    at cu (https://discord.com/assets/2276137a5d7df04f45db.js:2:3251654)
    at https://discord.com/assets/2276137a5d7df04f45db.js:2:3208463
    at t.unstable_runWithPriority (https://discord.com/assets/2276137a5d7df04f45db.js:2:3286470)
    at zi (https://discord.com/assets/2276137a5d7df04f45db.js:2:3208172)
    at Ji (https://discord.com/assets/2276137a5d7df04f45db.js:2:3208408)
    at Qi (https://discord.com/assets/2276137a5d7df04f45db.js:2:3208343)
    at du (https://discord.com/assets/2276137a5d7df04f45db.js:2:3252149)
    at Function.t.emitChanges (https://discord.com/assets/2276137a5d7df04f45db.js:2:733144)
    at e.t._dispatch (https://discord.com/assets/2276137a5d7df04f45db.js:2:2899343)
    at e._dispatch (D:\Downloads\EnhancedDiscord\plugins\0PluginLibrary.plugin.js:1905:73)
    at e.t.dispatch (https://discord.com/assets/2276137a5d7df04f45db.js:2:2898699)
    at e.t.dirtyDispatch (https://discord.com/assets/2276137a5d7df04f45db.js:2:2898658)
    at callOriginalMethod (D:\Downloads\EnhancedDiscord\plugins\0BDFDB.plugin.js:2057:90)
    at D:\Downloads\EnhancedDiscord\plugins\0BDFDB.plugin.js:217:15
    at e.module.<computed> [as dirtyDispatch] (D:\Downloads\EnhancedDiscord\plugins\0BDFDB.plugin.js:2072:159)
    at https://discord.com/assets/2276137a5d7df04f45db.js:2:1735105
e.exports @ 2276137a5d7df04f45db.js:2
t._dispatch @ 2276137a5d7df04f45db.js:2
(anonymous) @ D:\Downloads\EnhancedDiscord\plugins\0PluginLibrary.plugin.js:1905
t.dispatch @ 2276137a5d7df04f45db.js:2
(anonymous) @ 2276137a5d7df04f45db.js:2
u @ 2276137a5d7df04f45db.js:2
(anonymous) @ 2276137a5d7df04f45db.js:2
forEach.e.<computed> @ 2276137a5d7df04f45db.js:2
_ @ 2276137a5d7df04f45db.js:2
a @ 2276137a5d7df04f45db.js:2
(anonymous) @ 2276137a5d7df04f45db.js:2
(anonymous) @ 2276137a5d7df04f45db.js:2
N @ 2276137a5d7df04f45db.js:2
t.fetchSubscriptions @ 2276137a5d7df04f45db.js:2
(anonymous) @ cb8adf5de513780a5699.js:2
gs @ 2276137a5d7df04f45db.js:2
Cu @ 2276137a5d7df04f45db.js:2
t.unstable_runWithPriority @ 2276137a5d7df04f45db.js:2
zi @ 2276137a5d7df04f45db.js:2
Lu @ 2276137a5d7df04f45db.js:2
cu @ 2276137a5d7df04f45db.js:2
(anonymous) @ 2276137a5d7df04f45db.js:2
t.unstable_runWithPriority @ 2276137a5d7df04f45db.js:2
zi @ 2276137a5d7df04f45db.js:2
Ji @ 2276137a5d7df04f45db.js:2
Qi @ 2276137a5d7df04f45db.js:2
du @ 2276137a5d7df04f45db.js:2
t.emitChanges @ 2276137a5d7df04f45db.js:2
t._dispatch @ 2276137a5d7df04f45db.js:2
(anonymous) @ D:\Downloads\EnhancedDiscord\plugins\0PluginLibrary.plugin.js:1905
t.dispatch @ 2276137a5d7df04f45db.js:2
t.dirtyDispatch @ 2276137a5d7df04f45db.js:2
callOriginalMethod @ D:\Downloads\EnhancedDiscord\plugins\0BDFDB.plugin.js:2057
(anonymous) @ D:\Downloads\EnhancedDiscord\plugins\0BDFDB.plugin.js:217
module.<computed> @ D:\Downloads\EnhancedDiscord\plugins\0BDFDB.plugin.js:2072
(anonymous) @ 2276137a5d7df04f45db.js:2
Promise.then (async)
(anonymous) @ 2276137a5d7df04f45db.js:2
processImmediate @ internal/timers.js:439
Show 6 more frames
31296b03bdb291fe6072.js:2 GET https://discord.com/api/v8/channels/814750260572192778 403
(anonymous) @ 31296b03bdb291fe6072.js:2
(anonymous) @ 31296b03bdb291fe6072.js:2
v._end @ 2276137a5d7df04f45db.js:2
v.end @ 2276137a5d7df04f45db.js:2
r.default.Request.end @ 2276137a5d7df04f45db.js:2
(anonymous) @ 2276137a5d7df04f45db.js:2
o.then @ 2276137a5d7df04f45db.js:2
e @ 2276137a5d7df04f45db.js:2
(anonymous) @ 2276137a5d7df04f45db.js:2
p @ 2276137a5d7df04f45db.js:2
E @ 2276137a5d7df04f45db.js:2
(anonymous) @ cb8adf5de513780a5699.js:2
gs @ 2276137a5d7df04f45db.js:2
Cu @ 2276137a5d7df04f45db.js:2
t.unstable_runWithPriority @ 2276137a5d7df04f45db.js:2
zi @ 2276137a5d7df04f45db.js:2
Lu @ 2276137a5d7df04f45db.js:2
(anonymous) @ 2276137a5d7df04f45db.js:2
x @ 2276137a5d7df04f45db.js:2
A.port1.onmessage @ 2276137a5d7df04f45db.js:2
31296b03bdb291fe6072.js:2 Uncaught TypeError: Cannot read property 'accounts' of undefined
    at updateAvatars (D:\Downloads\EnhancedDiscord\plugins\AccountSwitcher.plugin.js:173)
    at r (31296b03bdb291fe6072.js:2)
    ```
